version: "3.9"

services:
  commit-sync:
    build: .
    image: openproject-commit-sync:latest
    container_name: commit-sync
    env_file:
      - .env
    depends_on:
      - web
    ports:
      - "8088:8088"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8088"]
    restart: unless-stopped
    networks:
      - frontend
    # Если вы используете caddy-docker-proxy (Caddy с docker-плагином),
    # можно раскомментировать labels ниже, чтобы отдать путь /github-webhook
    # через Caddy на этот сервис. Требуется корректная настройка хоста.
    # labels:
    #   - "caddy=${OPENPROJECT_HOST__NAME:-openproject.yourdomain.com}"
    #   - "caddy.route.0=/github-webhook*"
    #   - "caddy.route.0.reverse_proxy={{upstreams 8088}}"
    #   - "caddy.route.1=/gitlab-webhook*"
    #   - "caddy.route.1.reverse_proxy={{upstreams 8088}}"

  # Сервис web определяется в базовом docker-compose OpenProject.
  # depends_on помогает запускать commit-sync после основного веб-приложения.

networks:
  frontend:
    external: true
